#!/usr/bin/bash
POKEMON_API="https://pokeadi.co/api/v2/pokemon/"
POKEMON_NAME="pikachu"
FINAL_URL="$POKEMON_API$POKEMON_NAME"
curl -s -o data.json "$FINAL_URL"
if [ $? -ne 0 ]; then
	echo "[$(date)] Failed to fetch data $FINAL_URL" >> "errors.text"
else
	echo "Data successfully saved to data.json"
fi
