#!/usr/bin/env bash

DATA_DIR="."
OUTPUT_FILE="pokemon_report.csv"

echo "Name,Height (m),Weight (kg)" > $OUTPUT_FILE

for file in "$DATA_DIR"/*.json; do
	name=$(jq -r '.name' "$file" | sed 's/\b\(.\)/\u\1/g')
	height=$(jq -r '.height' "$file" | awk '{printf "%d", $1 / 10}')
	weight=$(jq -r '.weight' "$file" | awk 'printf "%.1f", $1 / 10}')

	printf "%s,%.1f,%.1f\n" "$name" "$height" "$weight" >> "$OUTPUT_FILE"
done

echo "CSV Report generated at: $OUTPUT_FILE"
echo ""

awk -F 'NR>1 {height+=$2; weight+=$3; count++}
END {
	printf "Average Height: %.2f m\n", height/count;
	printf "Average Weight: %.2f kg\n", weight/count
}' "$OUTPUT_FILE"
