#!/usr/bin/bash
POKEMON_API=https://pokeapi.co/api/v2/pokemon/
echo $POKEMON_API

echo -e "\nWhat's your name?\n"
read name
echo -e "\nWelcome $name\n"

echo You can run the script with arguments

echo "This is the first argument: $1"

if [ "$1" = "hello" ];
then echo "Is that your name?"
elif [ "$1" = "yes" ];
then echo "Alright, have a nice day!"
else
echo "I can't relate to your argument"
fi

i=1

while [[ $i -lt  10 ]]; do
	echo $i
	(( i += 1 ))
done;

shopt -s nocasematch

echo Enter a fruit you like

read fruit

case $fruit in
	"apple")
		echo "This is a red fruit"
		;;
	"orange")
		echo "An orange fruit. I love oranges too"
		;;
	"banana")
		echo "A yellow fruit"
		;;
	*)
		echo "I don't recognize this fruit"
		;;
esac
